name: build

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
           docker build .